- name: Ensure neccessary directory exist
  ansible.builtin.file:
      dest: '{{ item }}'
      state: directory
  loop:
      - '{{ HOME }}/.scripts'
      - '{{ XDG_CONFIG_HOME }}'
      - '{{ XDG_DATA_HOME }}'
      - '{{ XDG_CACHE_HOME }}'
