- name: Installing hyprland packages for arch
  become: true
  community.general.pacman:
      update_cache: true
      state: 'latest'
      name:
          - hyprutils
          - hyprlang
          - hyprwayland-scanner
          - hyprcursor
          - aquamarine
          - hyprland
          - hyprpaper
          - hypridle
          - hyprlock
          - xdg-desktop-portal-hyprland
  tags:
      - hypwm
