- name: Installing hyprland packages using pacman
  become: true
  community.general.pacman:
      update_cache: true
      state: 'latest'
      name:
          - hyprland
          - hyprlock
          - hyprpaper
          - hypridle
          - xdg-desktop-portal-hyprland
  tags:
      - hyprland

- name: Installing hyprland package dependencies using pacman
  become: true
  community.general.pacman:
      update_cache: true
      state: 'latest'
      name:
          - wl-clipboard
          - cliphist
          - polkit-gnome
          - qt5-wayland
          - qt6-wayland
          - socat
          - noise-suppression-for-voice
          - xwaylandvideobridge
          - playerctl
          - brightnessctl
          - libappindicator-gtk3
  tags:
      - hyprland
