- name: Download forbidden installsripts
  ansible.builtin.git:
      repo: 'git@github.com:SwollenBadger/.forbidden.git'
      dest: '{{ HOME }}/.forbidden'
      depth: 1
      update: false
      accept_hostkey: true
  tags:
      - personal
