- name: Link program to approriate name in ubuntu
  become: true
  ansible.builtin.file:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
      state: 'link'
  loop:
      - {src: '/usr/bin/batcat', dest: '/usr/bin/bat'}
      - {src: '/usr/bin/fdfind', dest: '/usr/bin/fd'}
  tags:
      - common
